### PR TITLE
auto-scaler types

### PR DESCRIPTION
**Pull request by pweil-**
Pre-PR review for the auto-scaler

@smarterclayton @pmorie - my plan of attack is to submit PRs in this order to keep them small(ish):
1.  types/rest/validation (included in this PR) - starting with intention based thresholds since that seemed to be the more relevant type (vs value based)
2.  kubectl wiring - printer, wiring in master.go/client.go
3.  concrete implementations

If this generally looks good to you I'll submit the PR for real.

### CODE REVIEW

**Comment by pmorie** [comment]
@pweil- I would long types and rest/validations into one PR

**Comment by pweil-** [comment]
Ok, combined 1 & 2.  Types, rest, and validation are now include (along with unit tests for validation and conversion/fuzzer utility methods).  Working on the registry items that round out the implementation

**Comment by pweil-** [comment]
@smarterclayton @ironcladlou @markturansky @derekwaynecarr - I've updated the PR based on @pmorie 's suggestion.  PTAL, if this looks like it's heading the right direction I'll make a real PR.

(This is the 1st round implementation of https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/proposals/autoscaling.md)

**Comment by pweil-** [comment]
Closing and opening main PR for some feedback

**Pull request closed without merging**
